name: Test & Build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build container
        run: docker build -t patrickjahns/ansible-later-action:${{ github.sha }} .
      - name: test container
        run: docker run -e GITHUB_WORKSPACE=/tmp --rm patrickjahns/ansible-later-action:${{ github.sha }}
